### PR TITLE
Updated Pd Core binaries

### PR DESCRIPTION
**Pull request by tkirshboim**
Hey there! Nice work. I could assemble an .aar file from the command line as well as from Android Studio with this branch. I saw that the PdCore submodule was updated but not the binaries, so I recompiled them and updated the branch.
Maybe you could merge this to your branch and update the pull request so it would contain it as well? I hope someone from the pd-for-android contributors would have a look at this sometime soon. Cheers!

https://github.com/libpd/pd-for-android/pull/10

### CODE REVIEW

**Comment by joebowbeer** [comment]
Thanks. Looking closer, I realized that NDK clean/build were not triggered by Gradle clean/build. I'd like the build.gradle to handle everything, so I'm working on that now.

In the future, shouldn't the aar (published to some maven repo) be the only artifact that contains native libraries?

**Comment by tkirshboim** [comment]
Yes, having an .aar on a maven repo would be great and would make it much simpler for people to use pd-for-android.
I wanted to try out  the changes you made to the gradle_mods branch, however I checked out the branch and there seems to be a problem with the references to the submodules. I ran `git submodule update --init --recursive` on the base folder of the repository and received these messages:

```
fatal: reference is not a tree: d377daf1c0fbd58d2a87b67487b70f97a66e6a1d
Unable to checkout '47b0765167af58dd54fe52cc0d811e4419c42bcb' in submodule path 'PdCore/jni/libpd'
Unable to checkout 'd377daf1c0fbd58d2a87b67487b70f97a66e6a1d' in submodule path 'midi'
```

**Comment by joebowbeer** [comment]
I added ndk-build (and clean) to build.gradle on my branch, and pushed the rebuilt .so files.
I also updated README.md.

I noticed that the Makefile in PdCore calls ndk-build and then copies libexpr.so to libexpr_tilde.so and libfexpr_tilde.so. These binaries were missing from your original pull request. I added an extra step to the ndkBuild task to make the copies.

**Comment by tkirshboim** [comment]
Great. What about the comment I wrote above? I'd like to test the branch to see that everything is working :)

**Comment by tkirshboim** [comment]
ah ok. just saw your comment on the pull request on the base pd-for-android repo

**Comment by joebowbeer** [comment]
I may have fixed the submodule pointers in the last commit. I'm trying to revert them to their HEAD revisions; this pull request doesn't change anything in those modules.

**Pull request closed without merging**
